TENANT_ID = "e93b9fed-7dfb-4dd3-8263-c783d68b2acd"
CLIENT_ID = "b38be07a-9fa5-469f-8792-4bc1b1e474a3"
CLIENT_SECRET = "1fR8Q~kz57YLWqnLLeiwc.B96Pjw.2tg-Y5nrakH" 
SITE_URL = "https://fbsnext.sharepoint.com/sites/Fbsnextspa"
LIBRARY_NAME= "Shared Documents"
FOLDER_PATH= "General/PRENOTAZIONI_BI"
DT_FOLDER_PATH= "General/DIFFIDE_TELEGRAMMI"


FIREBASE_API_KEY= "AIzaSyAah8IMClsEb6MEIu538mUnl8_imDKbPcU"

[firebase_key]
type = "service_account"
project_id = "prenotazioni-bi"
private_key_id = "78b29a8b70f70227cf02e01ef224625aaa21cf85"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCOGd5kUTJt1SJf\n2yuOniPhJICMeydxGLayFig9u7wyGZtezG9GZyt5On7BQ29a25bIxzXcXSoiCaKJ\ne7EU+kfCTl3QKTvfisM1NFcNf+NtMeaIg+3NPKak0SGvPMT8+vlW4CqsNIcjVR2n\nUc/3Y2Yf9Arb+UW5Ryj5xIisZvPXvtFv/ZnY4GmXzh1j1i63j6F1hJrJEKIF+4io\n4TQ4gQ81o6CrReCOrtdowb1SgzVgfp6CqA27HHlDOUeZbisiKh0PMuMKDpELnm+1\n2+ZWkIM8OuiJihkUfDRO5XhCY53pjhAbLRv15XEhrK/ApTVdFRxqp4lVi+cxbjG8\nsQ8RcTV/AgMBAAECggEAGA9gPNsUr00Vp2ZMLzcuewn7rA2UJY2aLXgb8yvs1wzH\n5lq2ApUoYrvZR27cFWW116QHRhsOLbo055NmbddcvBUZxEufBCASIlmM3c/IGa6H\nypiP9J6u1pxEWE/xSKZT/nYxM3wnX3+jaDetf0U4vvNKvWks+YyHbxbsT0iVQ/Oe\nEKrmzEeQp3gN1+JaAsyixV4j4THdP5OaB7YqB5BAH9PVBm5/bMLh0QwGlq9JSjo2\nOMj8LneeZkfydwdMKwy6Zs8/t+HFQSSyKpuiY70q3VUfxxavZEjZl3DtgmPZcen2\n9FlMf63kI8IrhyHLPZeUTttXM4WI6NqM+2U5VkjjtQKBgQDFlD3euP0ms5QWj7jx\nOqrje7RRuP+bKjSJY4Aso2Eau7lAn1bRUVpL6gB62wXuAkD5qyy1KELEGfuGW/vy\nTZZdQ0nIis9jvv9hLSPR3LlZAcYtT2HlC9VgS67Du++OaQHHzMUy78yga0eDyOQd\n/UvCmxTX6j0/ofALw5CVggBlYwKBgQC4Hjch3Te2OCbZF9I3xkPtvi3IpUG6xh4k\nlH6H8MzFQtAi1b23I7cQorybmw4gYQJatIxuKydjeKoWZKjh83WNHyUV8v2tV3cs\nLCRz9JiwJtLJXUhRT42C5u3Tvlsl/VlbkwXUibFTb+WKP9GOD+jeAV3uCicRQoT+\nEwHMJuRoNQKBgDrcQuJLMf+JmCBwiKQ02hwTClEeT+el1yjm35Rsx8zzB+lcjryl\nA8WB3Mq83TNesISwng0KBXnuU6RfWtuAib8XALAhyk7o46PLktQ+cWk2whdVgtB9\nif+6DEJ7ho5icglX05etIMTZsOBtxKe6ggtjr/3y5nRChgS7KiOgKwYJAoGASOF9\nBWSh5vl3NzwctINA5F0BlokD6cD+sZAuPfVtuS/nX8Kn5FS45Fbmvdm0z9BWtDz/\n0aQ3ZUKgYVjbGQXcJE6NyZB0JieXPt8CVvwdbK0Rhy/rrnQFGin7PnP9dJ5CvuMF\nzcnrbZG/lOgKNWfK0AZOfil6qXRhXIl9jqhehXkCgYEAsq1eKCzFfDOzBKbM8THf\nHp0yNejFhXWAqQ+YqNxc8wscVwlhHGaJsqgQq7J01REEHSsMQEDVmJ4RanTGyLdR\neWnL1Ex9wqHm1P+pKRcAHSXVCW75gfmH0c4eSYK8n3IqD2EYTzbXg6++HZlgHmor\nJLq8mHH0cmbzCZx7R9DpQmg=\n-----END PRIVATE KEY-----\n"""
client_email = "firebase-adminsdk-fbsvc@prenotazioni-bi.iam.gserviceaccount.com"
client_id = "106511179617415701156"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40prenotazioni-bi.iam.gserviceaccount.com"
universe_domain = "googleapis.com"